version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./nginx.d/pokedraft-prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment: {}
    networks:
      - drafts
    links:
      - app
      - gui
  app:
    image: pokedraft/app:v0.1
    networks:
      - drafts
  gui:
    image: pokedraft/gui:v0.1
    networks:
      - drafts
networks:
  drafts: {}
