name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  IMAGE_NAME: pokedraft-gui
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
    - name: Log in to repository
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push image
      run: |
        VERSION=$(cat package.json | jq -r .version)
        [[ "$BRANCH_NAME" != "main" ]] && VERSION="$VERSION-$BRANCH_NAME"
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION="v$VERSION"
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        if [ "$BRANCH_NAME" == "main" ]; then 
          docker tag $IMAGE_NAME $IMAGE_ID:latest 
          docker push $IMAGE_ID:latest
        fi
